[project]
name = "protein-ensemble"
version = "0.1.0"
description = "Protein Ensemble Spec Python SDK"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Mike Micatka", email = "mike.micatka@gmail.com" }]
license = { text = "MIT" }

dependencies = ["blake3>=1.0.9", "fsspec>=2026.7.0"]

[project.scripts]
generate-manifest = "protein_ensemble.cli:generate_manifest"

[project.optional-dependencies]
s3 = ["fsspec[s3]>=2026.7.0"]
pdbqt = ["gemmi>=0.7.5", "meeko>=0.8.0"]
cli = ["click>=8.5.0"]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
codegen = ["datamodel-code-generator[http]>=0.76.0"]
dev = ["pre-commit>=4.6.2", "pyright>=1.1.411", "ruff>=0.16.5"]

[tool.datamodel-codegen]
input = "schemas/v0/manifest.schema.json"
input-file-type = "jsonschema"

output = "src/protein_ensemble/models.py"
output-model-type = "pydantic_v2.BaseModel"

preset = "standard-py312-20260826"
formatters = ["ruff-check", "ruff-format"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "C4",     # flake8-comprehensions
    "C90",    # mccabe
    "D212",   # pydocstyle: multi-line docstring summary should start at the first line
    "E",      # pycodestyle
    "F",      # pyflakes
    "I",      # isort
    "PERF",   # Perflint
    "UP",     # pyupgrade
    "TID251", # https://docs.astral.sh/ruff/rules/banned-api/
]

[tool.ruff.lint.per-file-ignores]
# generated code
"src/protein_ensemble/models.py" = ["D212", "E501", "I001", "UP007", "UP037"]
