# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class TopologyReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    member_id: Annotated[str, Field(alias="memberId")]


class ExternalReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    uri: str
    source: str | None = None


class TopologyReference1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    external_reference: Annotated[ExternalReference, Field(alias="externalReference")]


class Type(StrEnum):
    equilibrium_probability = "EQUILIBRIUM_PROBABILITY"
    cluster_fraction = "CLUSTER_FRACTION"
    experimental_occupancy = "EXPERIMENTAL_OCCUPANCY"
    uniform = "UNIFORM"
    custom = "CUSTOM"


class WeightScheme(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Type
    normalized: bool | None = None
    custom_semantics: Annotated[Any | None, Field(alias="customSemantics")] = None


class Structure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    uri: str


class Structure1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    uri: str
    model_index: Annotated[int, Field(alias="modelIndex", ge=0)]


class TrajectoryFormat(StrEnum):
    xtc = "XTC"
    dcd = "DCD"
    trr = "TRR"
    nc = "NC"


class Structure2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    topology_uri: Annotated[str, Field(alias="topologyUri")]
    trajectory_uri: Annotated[str, Field(alias="trajectoryUri")]
    frame_index: Annotated[int, Field(alias="frameIndex", ge=0)]
    trajectory_format: Annotated[TrajectoryFormat, Field(alias="trajectoryFormat")]


class Weight(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    type: str | None = None


class ResidueMapping(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    uri: str
    format: str | None = None


class Member(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: Annotated[
        str,
        Field(
            description="Unique member ID matching alphanumeric, hyphen, and underscore characters.",
            pattern="^[a-zA-Z0-9_-]+$",
        ),
    ]
    structure: Structure | Structure1 | Structure2
    weight: Weight | None = None
    residue_mapping: Annotated[ResidueMapping | None, Field(alias="residueMapping")] = (
        None
    )
    thermodynamics: Annotated[
        dict[str, Any] | None,
        Field(description="Opaque passthrough for thermodynamics."),
    ] = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    schema_version: Annotated[
        Literal["0.1.0"],
        Field(
            alias="schemaVersion", description="The current manifest schema version."
        ),
    ]
    id: Annotated[str, Field(description="Unique ensemble ID.")]
    content_hash: Annotated[
        str,
        Field(
            alias="contentHash",
            description="Content hash in the format algorithm:hexdigest.",
            pattern="^[a-zA-Z0-9_-]+:[a-fA-F0-9]+$",
        ),
    ]
    topology_reference: Annotated[
        TopologyReference | TopologyReference1,
        Field(
            alias="topologyReference",
            description="Identifies the topology against which ensemble members are interpreted.",
        ),
    ]
    weight_scheme: Annotated[WeightScheme | None, Field(alias="weightScheme")] = None
    capabilities_required: Annotated[list[str], Field(alias="capabilitiesRequired")] = [
        "STANDALONE_CIF"
    ]
    metadata: Annotated[
        dict[str, Any] | None, Field(description="Opaque passthrough for metadata.")
    ] = None
    dynamics: Annotated[
        dict[str, Any] | None, Field(description="Opaque passthrough for dynamics.")
    ] = None
    members: Annotated[list[Member], Field(min_length=1)]
