# generated by datamodel-codegen:
#   filename:  manifest.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class CapabilitiesRequiredItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Type(StrEnum):
    uniform = "UNIFORM"
    equilibrium_probability = "EQUILIBRIUM_PROBABILITY"


class WeightScheme(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Annotated[Type, Field(description="Defines how member weights are interpreted.")]
    normalized: Annotated[
        bool | None,
        Field(description="Whether explicit member weights are normalized according to the semantic contract."),
    ] = None


class Structure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    uri: Annotated[
        str,
        Field(
            description="URI reference to the structural resource. Relative references are resolved"
            " relative to the manifest.",
            min_length=1,
        ),
    ]
    model_index: Annotated[
        int | None,
        Field(
            alias="modelIndex",
            description="Zero-based model index within the referenced structural resource. When omitted,"
            " the referenced resource represents a single structural member.",
            ge=0,
        ),
    ] = None


class Weight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    value: Annotated[
        float,
        Field(
            description="Member weight. Its interpretation and permitted range are defined by weightScheme"
            " and the semantic contract."
        ),
    ]


class Member(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    structure: Structure
    structure_hash: Annotated[
        str,
        Field(
            alias="structureHash",
            description="Content identifier for the referenced structural resource, in the form algorithm:hexdigest.",
            pattern="^[A-Za-z0-9_-]+:[A-Fa-f0-9]+$",
        ),
    ]
    weight: Weight | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    schema_version: Annotated[
        Literal["0.1.0"],
        Field(alias="schemaVersion", description="Version of the Protein Ensemble manifest specification."),
    ]
    id: Annotated[
        str,
        Field(
            description="Identifier for the ensemble within its managing namespace.",
            min_length=1,
            pattern="^[A-Za-z0-9_-]+$",
        ),
    ]
    content_hash: Annotated[
        str,
        Field(
            alias="contentHash",
            description="Content identifier for the ensemble, in the form algorithm:hexdigest.",
            pattern="^[A-Za-z0-9_-]+:[A-Fa-f0-9]+$",
        ),
    ]
    weight_scheme: Annotated[WeightScheme | None, Field(alias="weightScheme")] = None
    capabilities_required: Annotated[
        list[CapabilitiesRequiredItem] | None,
        Field(
            alias="capabilitiesRequired", description="Capabilities a consumer must support to interpret this manifest."
        ),
    ] = None
    metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description="Non-normative metadata. Metadata fields have no PE core semantic meaning unless"
            " explicitly defined by the specification."
        ),
    ] = None
    members: dict[str, Member]
